### PR TITLE
Colinbr

### PR DESCRIPTION
**Pull request by Cojabi**
pls pull in my stuff

### CODE REVIEW

**Comment by Cojabi** [comment]
i tink tis good idear

**Comment by Cojabi** [comment]
*tis*

**Comment by Cojabi** [comment]
## good idea

**Review by Oli4 — CHANGES_REQUESTED** [review]
You have to add the notbooks checkpoint folder to the .gitignore and remove the .ipynb_checkpoints folder

**Review by Oli4 — APPROVED** [review]

**Pull request merged**
